using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Practice.xmlParsing
{
    class StaticXML
    {
        public static string xmlLoanNotFoundText = @"<RESPONSE>
	<CONTROL>
		<ORIGINATOR>GROWINGPOINT</ORIGINATOR>
		<ORIGIN_DATETIME>Fri Feb 17 08:57:02 CST 2017</ORIGIN_DATETIME>
		<SERVICE>LMS</SERVICE>
		<FUNCTION>LOAN_DETAIL_LOOKUP</FUNCTION>
		<DESTINATION>
			<INSTANCE>DV</INSTANCE>
			<CLIENT>999</CLIENT>
		</DESTINATION>
		<VERSION>1.0</VERSION>
		<PERSISTENCE>N</PERSISTENCE>
		<REALTIME>Y</REALTIME>
		<AUDIT_LOG>Y</AUDIT_LOG>
		<ORIGINAL_REPLYQ>EAI.HTTP.RESPONSE</ORIGINAL_REPLYQ>
	</CONTROL>
	<STATUS>
		<CODE>0</CODE>
		<DESCRIPTION>Loan details were not found for Account Number = null 12345</DESCRIPTION>
		<CREATE_DATETIME>20170217 08:57:02.409</CREATE_DATETIME>
		<RESPONSE_GMTTIME>14:57:02.493017</RESPONSE_GMTTIME>
	</STATUS>
	<APP>
		<LMS_STATUS>1</LMS_STATUS>
		<LMS_STATUS_REASON>0</LMS_STATUS_REASON>
	</APP>
</RESPONSE>";

        public static string xmlFullText = @" <RESPONSE>
	<CONTROL>
		<ORIGINATOR>GROWINGPOINT</ORIGINATOR>
		<ORIGIN_DATETIME>Thu Feb 16 14:02:46 CST 2017</ORIGIN_DATETIME>
		<SERVICE>LMS</SERVICE>
		<FUNCTION>LOAN_DETAIL_LOOKUP</FUNCTION>
		<DESTINATION>
			<INSTANCE>DV</INSTANCE>
			<CLIENT>999</CLIENT>
		</DESTINATION>
		<VERSION>1.0</VERSION>
		<PERSISTENCE>N</PERSISTENCE>
		<REALTIME>Y</REALTIME>
		<AUDIT_LOG>Y</AUDIT_LOG>
		<ORIGINAL_REPLYQ>EAI.HTTP.RESPONSE</ORIGINAL_REPLYQ>
	</CONTROL>
	<STATUS>
		<CODE>0</CODE>
		<DESCRIPTION>COMPLETED</DESCRIPTION>
		<CREATE_DATETIME>20170216 14:02:46.184</CREATE_DATETIME>
		<RESPONSE_GMTTIME>20:02:47.844060</RESPONSE_GMTTIME>
	</STATUS>
	<APP>
		<LMS_STATUS>0</LMS_STATUS>
		<LMS_STATUS_REASON>0</LMS_STATUS_REASON>
		<ADDRESS_VO>
			<COMPANY_NAME>Troyer Farms LLC</COMPANY_NAME>
			<FIRST_NAME>Steve</FIRST_NAME>
			<LAST_NAME>Troyer</LAST_NAME>
			<ADDRESS_1>17905 Troyer Rd</ADDRESS_1>
			<CITY>White Hall</CITY>
			<STATE>MD</STATE>
			<POSTAL_CODE>21161</POSTAL_CODE>
			<COUNTRY>US</COUNTRY>
			<PHONE_NUMBERS>
				<PHONE_TYPE_CD>01</PHONE_TYPE_CD>
				<PHONE_NBR>4106925434</PHONE_NBR>
				<PHONE_TYPE_DESC>Home</PHONE_TYPE_DESC>
			</PHONE_NUMBERS>
			<PHONE_NUMBERS>
				<PHONE_TYPE_CD>02</PHONE_TYPE_CD>
				<PHONE_NBR>4106925434</PHONE_NBR>
				<PHONE_TYPE_DESC>Work</PHONE_TYPE_DESC>
			</PHONE_NUMBERS>
		</ADDRESS_VO>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>0.0</TOTAL_PRINCIPAL>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>0.0</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>16975764</LOAN_ID>
					<LOAN_YEAR>2017</LOAN_YEAR>
					<LOAN_TYPE>8</LOAN_TYPE>
					<LOAN_STATUS>Not Applicable</LOAN_STATUS>
					<ORIGIN_CD>6</ORIGIN_CD>
					<NAS_PROGRAM_CD>TC</NAS_PROGRAM_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<EPS_AMT>0</EPS_AMT>
					<MATURITY_DATE>2017-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<CREDIT_LIMIT>0</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Not Applicable</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>0.0</TOTAL_PRINCIPAL>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>0.0</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>16907097</LOAN_ID>
					<LOAN_YEAR>2016</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Pending</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<NAS_PROGRAM_CD>DA</NAS_PROGRAM_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<EPS_AMT>0</EPS_AMT>
					<MATURITY_DATE>2016-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<CREDIT_LIMIT>459000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>-1</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>0.0</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>500.0</CHEMICAL_USAGE>
				<SEED_USAGE>0.0</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>16975649</LOAN_ID>
					<LOAN_YEAR>2015</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Not Applicable</LOAN_STATUS>
					<ORIGIN_CD>4</ORIGIN_CD>
					<LMS_INT_RATE_CD>119</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>CC</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>119</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>2427.6</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>110.14</ACCRUED_INT_AMT>
					<EPS_AMT>0</EPS_AMT>
					<MATURITY_DATE>2015-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<CREDIT_LIMIT>0</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>2</SEASON_CD>
					<SEASON_DESC>Fall</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Not Applicable</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>0.0</TOTAL_PRINCIPAL>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>0.0</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>14171863</LOAN_ID>
					<LOAN_YEAR>2015</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Pending</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<NAS_PROGRAM_CD>DA</NAS_PROGRAM_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<EPS_AMT>0</EPS_AMT>
					<MATURITY_DATE>2015-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<CREDIT_LIMIT>459000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>-1</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>0.0</TOTAL_PRINCIPAL>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>0.0</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>16902356</LOAN_ID>
					<LOAN_YEAR>2015</LOAN_YEAR>
					<LOAN_TYPE>8</LOAN_TYPE>
					<LOAN_STATUS>Not Applicable</LOAN_STATUS>
					<ORIGIN_CD>6</ORIGIN_CD>
					<NAS_PROGRAM_CD>TC</NAS_PROGRAM_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<EPS_AMT>0</EPS_AMT>
					<MATURITY_DATE>2015-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<CREDIT_LIMIT>0</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Not Applicable</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>0.0</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>371040.52</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>13680443</LOAN_ID>
					<LOAN_YEAR>2014</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<LMS_INT_RATE_CD>226</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>DZ</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>065</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>376068.52</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.326-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>0</EPS_AMT>
					<MATURITY_DATE>2014-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2014-12-02T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>407000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>-1</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>-399325.62</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>395167.62</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>13209731</LOAN_ID>
					<LOAN_YEAR>2013</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<LMS_INT_RATE_CD>226</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>DZ</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>065</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.374-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>41051.06</EPS_AMT>
					<MATURITY_DATE>2013-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2013-12-07T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>400000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LAST_PAYMENT_DATE>2013-12-03T00:00:00.000-06:00</LAST_PAYMENT_DATE>
			<LAST_PAYMENT_AMT>-399325.62</LAST_PAYMENT_AMT>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>-164.35</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>-328560.97</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>328715.32</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>12895290</LOAN_ID>
					<LOAN_YEAR>2012</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<LMS_INT_RATE_CD>226</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>DZ</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>065</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.396-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>33752.08</EPS_AMT>
					<MATURITY_DATE>2012-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2012-12-02T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>330000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LAST_PAYMENT_DATE>2012-12-03T00:00:00.000-06:00</LAST_PAYMENT_DATE>
			<LAST_PAYMENT_AMT>-328725.32</LAST_PAYMENT_AMT>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>-269105.45</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>269095.45</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>12457770</LOAN_ID>
					<LOAN_YEAR>2011</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<LMS_INT_RATE_CD>001</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>DZ</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>065</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.418-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>29898.7</EPS_AMT>
					<MATURITY_DATE>2011-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2011-12-02T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>271000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LAST_PAYMENT_DATE>2011-12-01T00:00:00.000-06:00</LAST_PAYMENT_DATE>
			<LAST_PAYMENT_AMT>-269105.45</LAST_PAYMENT_AMT>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>-244285.6</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>244275.6</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>12192802</LOAN_ID>
					<LOAN_YEAR>2010</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<LMS_INT_RATE_CD>001</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>DZ</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>065</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.444-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>25169.07</EPS_AMT>
					<MATURITY_DATE>2010-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2010-12-02T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>258000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LAST_PAYMENT_DATE>2010-12-20T00:00:00.000-06:00</LAST_PAYMENT_DATE>
			<LAST_PAYMENT_AMT>-2198.49</LAST_PAYMENT_AMT>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>-1432.2</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>-204413.44</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>204540.43</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>11872925</LOAN_ID>
					<LOAN_YEAR>2009</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<LMS_INT_RATE_CD>001</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>DZ</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>065</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.472-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>15652.17</EPS_AMT>
					<MATURITY_DATE>2009-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2009-12-03T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>235000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LAST_PAYMENT_DATE>2009-12-17T00:00:00.000-06:00</LAST_PAYMENT_DATE>
			<LAST_PAYMENT_AMT>-205845.64</LAST_PAYMENT_AMT>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>-7594.96</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>-148000.43</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>148052.09</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>11550822</LOAN_ID>
					<LOAN_YEAR>2008</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<LMS_INT_RATE_CD>053</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>DL</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>065</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.503-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>13345.73</EPS_AMT>
					<MATURITY_DATE>2008-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2008-12-08T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>228000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LAST_PAYMENT_DATE>2008-12-09T00:00:00.000-06:00</LAST_PAYMENT_DATE>
			<LAST_PAYMENT_AMT>-155595.39</LAST_PAYMENT_AMT>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>0.0</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>0.0</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>11827105</LOAN_ID>
					<LOAN_YEAR>2007</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Not Applicable</LOAN_STATUS>
					<ORIGIN_CD>4</ORIGIN_CD>
					<LMS_INT_RATE_CD>119</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>CC</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>119</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.530-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>0</EPS_AMT>
					<MATURITY_DATE>2008-03-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2008-03-01T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>0</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>2</SEASON_CD>
					<SEASON_DESC>Fall</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Not Applicable</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>-13378.29</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>-165435.32</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>165425.34</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>11263707</LOAN_ID>
					<LOAN_YEAR>2007</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<LMS_INT_RATE_CD>053</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>DL</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>065</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.557-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>9973.83</EPS_AMT>
					<MATURITY_DATE>2007-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2007-12-19T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>194000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LAST_PAYMENT_DATE>2008-01-16T00:00:00.000-06:00</LAST_PAYMENT_DATE>
			<LAST_PAYMENT_AMT>-78813.61</LAST_PAYMENT_AMT>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>-11375.72</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>-147220.2</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>147415.64</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>11021256</LOAN_ID>
					<LOAN_YEAR>2006</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<LMS_INT_RATE_CD>053</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>DL</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>065</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.584-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>7518.84</EPS_AMT>
					<MATURITY_DATE>2006-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2006-12-20T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>163000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LAST_PAYMENT_DATE>2006-12-26T00:00:00.000-06:00</LAST_PAYMENT_DATE>
			<LAST_PAYMENT_AMT>-58595.92</LAST_PAYMENT_AMT>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>-8971.7</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>-144031.19</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>143877.28</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>10734712</LOAN_ID>
					<LOAN_YEAR>2005</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>1</ORIGIN_CD>
					<SUB_ORIGIN_CD>1</SUB_ORIGIN_CD>
					<LMS_INT_RATE_CD>531</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>DP</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>065</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.611-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>0</EPS_AMT>
					<MATURITY_DATE>2005-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2005-12-20T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>144000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LAST_PAYMENT_DATE>2006-01-03T00:00:00.000-06:00</LAST_PAYMENT_DATE>
			<LAST_PAYMENT_AMT>-78002.89</LAST_PAYMENT_AMT>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>-3902.25</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>-109025.7</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>108985.38</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>10669607</LOAN_ID>
					<LOAN_YEAR>2004</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>2</ORIGIN_CD>
					<SUB_ORIGIN_CD>8</SUB_ORIGIN_CD>
					<LMS_INT_RATE_CD>031</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>DN</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>065</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<LAST_INT_RUN_DT>2017-02-16T14:02:47.649-06:00</LAST_INT_RUN_DT>
					<EPS_AMT>4196.25</EPS_AMT>
					<MATURITY_DATE>2004-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<DEFAULT_DT>2004-12-15T00:00:00.000-06:00</DEFAULT_DT>
					<CREDIT_LIMIT>109000</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LAST_PAYMENT_DATE>2004-12-10T00:00:00.000-06:00</LAST_PAYMENT_DATE>
			<LAST_PAYMENT_AMT>-112927.95</LAST_PAYMENT_AMT>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Completed</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Application Reviewed</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
		<LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>0.0</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>0.0</CHEMICAL_USAGE>
				<SEED_USAGE>0.0</SEED_USAGE>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>10446679</LOAN_ID>
					<LOAN_YEAR>2001</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Not Applicable</LOAN_STATUS>
					<ORIGIN_CD>4</ORIGIN_CD>
					<LMS_INT_RATE_CD>119</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>CC</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>119</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<EPS_AMT>0</EPS_AMT>
					<MATURITY_DATE>2001-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<CREDIT_LIMIT>0</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Not Applicable</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
        <LOAN_DETAILS>
			<LOANPVO>
				<TOTAL_INTEREST>0.0</TOTAL_INTEREST>
				<TOTAL_PRINCIPAL>0.0</TOTAL_PRINCIPAL>
				<CURRENT_INT_RATE>
					<percent>0.18</percent>
				</CURRENT_INT_RATE>
				<CHEMICAL_USAGE>10.0</CHEMICAL_USAGE>
				<SEED_USAGE>0.0</SEED_USAGE>
                <LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>10446679</LOAN_ID>
					<LOAN_YEAR>2001</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Approved</LOAN_STATUS>
					<ORIGIN_CD>4</ORIGIN_CD>
					<LMS_INT_RATE_CD>119</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>CC</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>119</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<EPS_AMT>0</EPS_AMT>
					<MATURITY_DATE>2001-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<CREDIT_LIMIT>0</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
				<LOAN_DATA>
					<LOAN_CUST_ID>17004357</LOAN_CUST_ID>
					<LOAN_ID>10446679</LOAN_ID>
					<LOAN_YEAR>2001</LOAN_YEAR>
					<LOAN_TYPE>1</LOAN_TYPE>
					<LOAN_STATUS>Not Applicable</LOAN_STATUS>
					<ORIGIN_CD>4</ORIGIN_CD>
					<LMS_INT_RATE_CD>119</LMS_INT_RATE_CD>
					<NAS_PROGRAM_CD>CC</NAS_PROGRAM_CD>
					<DEFAULT_INT_RATE_CD>119</DEFAULT_INT_RATE_CD>
					<PRINCIPAL_BALANCE>0</PRINCIPAL_BALANCE>
					<ACCRUED_INT_AMT>0</ACCRUED_INT_AMT>
					<EPS_AMT>0</EPS_AMT>
					<MATURITY_DATE>2001-12-01T00:00:00.000-06:00</MATURITY_DATE>
					<CREDIT_LIMIT>0</CREDIT_LIMIT>
					<DAILY_ACCRUAL>0</DAILY_ACCRUAL>
					<CREDIT_BUREAU_SCORE>0</CREDIT_BUREAU_SCORE>
					<SEASON_CD>1</SEASON_CD>
					<SEASON_DESC>Spring</SEASON_DESC>
				</LOAN_DATA>
			</LOANPVO>
			<LOAN_TYPE_DESCRIPTION>Deferred Payment Loan</LOAN_TYPE_DESCRIPTION>
			<AGREEMENT_STATUS>Not Applicable</AGREEMENT_STATUS>
			<BALANCESHEET_STATUS>Not Applicable</BALANCESHEET_STATUS>
			<SECURED_LOAN_STATUS>Not Applicable</SECURED_LOAN_STATUS>
		</LOAN_DETAILS>
	</APP>
</RESPONSE>";
    }
}
